In [1]:
import pyforest

In [5]:
school = pd.read_csv('..\Data\California_School_Demographics.csv')

In [6]:
school.head()

,X,Y,OBJECTID,Year,FedID,CDSCode,CDCode,CountyName,DistrictName,SchoolName,...,CCPrepCohortCount,CCPrepPct,AbsentEligCount,AbsentPct,GradCohortCount,GradPct,UCCSUReqMetPct,DropOutPct,EnrollCumulative,SuspPct
0,-121.590439,39.153060,10001,2018-19,6.072601e+10,5.872729e+13,5872728.0,Yuba,Camptonville Elementary,CORE Charter,...,37.0,48.6,496.0,3.6,37.0,97.3,19.4,2.7,515.0,0.0
1,-121.549427,39.119801,10002,2018-19,6.240901e+10,5.872736e+13,5872736.0,Yuba,Marysville Joint Unified,Edgewater Elementary,...,NaN,NaN,503.0,4.4,NaN,NaN,NaN,NaN,517.0,1.9
2,-121.580742,39.153893,10003,2018-19,6.240901e+10,5.872736e+13,5872736.0,Yuba,Marysville Joint Unified,Paragon Collegiate Academy,...,NaN,NaN,202.0,10.4,NaN,NaN,NaN,NaN,215.0,10.2
3,-121.587390,39.156443,10004,2018-19,6.240901e+10,5.872736e+13,5872736.0,Yuba,Marysville Joint Unified,Marysville Community Day,...,NaN,NaN,140.0,53.6,NaN,NaN,NaN,NaN,175.0,29.1
4,-121.538152,39.083408,10005,2018-19,6.240900e+10,5.872737e+13,5872736.0,Yuba,Marysville Joint Unified,Lindhurst High,...,224.0,34.8,1203.0,20.3,224.0,86.6,34.5,8.9,1249.0,10.0

In [7]:
school.describe()

,X,Y,OBJECTID,FedID,CDSCode,CDCode,Latitude,Longitude,CongUS,SenateCA,...,CCPrepCohortCount,CCPrepPct,AbsentEligCount,AbsentPct,GradCohortCount,GradPct,UCCSUReqMetPct,DropOutPct,EnrollCumulative,SuspPct
count,10033.000000,10033.000000,10033.000000,1.003200e+04,1.003200e+04,1.003200e+04,10032.000000,10032.000000,10031.000000,10031.000000,...,2202.000000,2202.000000,9941.000000,9935.000000,2258.000000,2258.000000,2258.000000,2258.000000,9941.000000,9941.000000
mean,-119.592181,35.822549,5017.000000,6.243843e+10,2.923451e+13,2.923451e+06,35.822354,-119.592228,24.579304,18.691157,...,218.794732,32.515804,663.582537,15.415209,218.704163,74.906289,34.755359,13.492516,690.781813,3.817222
std,2.019892,2.208862,2896.421959,1.830033e+09,1.406465e+13,1.406465e+06,2.208886,2.020046,15.752544,11.868115,...,214.990292,27.289535,562.518326,17.282019,214.391761,27.054482,31.898145,17.451607,606.511079,6.478010
min,-124.284893,32.547895,1.000000,6.000010e+10,1.100170e+12,1.100170e+05,32.547895,-124.284900,1.000000,1.000000,...,11.000000,0.000000,0.000000,0.000000,11.000000,0.000000,0.000000,0.000000,11.000000,0.000000
25%,-121.596608,33.964054,2509.000000,6.118500e+10,1.964733e+13,1.964733e+06,33.964051,-121.596675,10.000000,8.000000,...,47.250000,2.600000,351.000000,6.200000,50.000000,61.125000,0.000000,2.000000,366.000000,0.400000
50%,-119.049831,34.927985,5017.000000,6.227101e+10,3.066648e+13,3.066647e+06,34.927912,-119.049950,23.000000,17.000000,...,124.000000,34.300000,554.000000,10.000000,121.000000,87.600000,34.800000,6.200000,573.000000,1.600000
75%,-117.945675,37.753454,7525.000000,6.338600e+10,3.773791e+13,3.773791e+06,37.753359,-117.945575,38.000000,29.000000,...,372.750000,53.875000,792.000000,16.100000,372.750000,94.975000,58.475000,19.000000,820.000000,4.700000
max,-114.395807,41.989053,10033.000000,6.911371e+10,5.872770e+13,5.872769e+06,41.989053,-114.395800,53.000000,40.000000,...,1130.000000,100.000000,6918.000000,100.000000,1401.000000,100.000000,100.000000,100.000000,12302.000000,81.000000

In [8]:
school.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10033 entries, 0 to 10032
Data columns (total 88 columns):
X                    10033 non-null float64
Y                    10033 non-null float64
OBJECTID             10033 non-null int64
Year                 10032 non-null object
FedID                10032 non-null float64
CDSCode              10032 non-null float64
CDCode               10032 non-null float64
CountyName           10032 non-null object
DistrictName         10032 non-null object
SchoolName           10032 non-null object
SchoolType           10032 non-null object
EduOption            10032 non-null object
Status               10032 non-null object
OpenDate             10032 non-null object
ClosedDate           104 non-null object
SchoolLevel          10032 non-null object
GradeLow             10032 non-null object
GradeHigh            10029 non-null object
Charter              10032 non-null object
CharterNum           1263 non-null object
FundingType          1262 non-null object
Virtual              10032 non-null object
Magnet               10022 non-null object
Street               10032 non-null object
City                 10032 non-null object
Zip                  10032 non-null object
State                10032 non-null object
Latitude             10032 non-null float64
Longitude            10032 non-null float64
LocSource            10032 non-null object
CountyGeo            10031 non-null object
Locale               10032 non-null object
CongUS               10031 non-null float64
SenateCA             10031 non-null float64
AssemblyCA           10031 non-null float64
DateUpdated          10032 non-null object
YearData             10032 non-null object
RecordType           10032 non-null object
EnrollTotal          10032 non-null float64
AAcount              10032 non-null float64
AApct                10031 non-null float64
AIcount              10032 non-null float64
AIpct                10031 non-null float64
AScount              10032 non-null float64
ASpct                10031 non-null float64
FIcount              10032 non-null float64
FIpct                10031 non-null float64
HIcount              10032 non-null float64
HIpct                10031 non-null float64
MRcount              10032 non-null float64
MRpct                10031 non-null float64
PIcount              10032 non-null float64
PIpct                10031 non-null float64
WHcount              10032 non-null float64
WHpct                10031 non-null float64
NRcount              10032 non-null float64
NRpct                10031 non-null float64
UPcount              10022 non-null float64
UPpct                10022 non-null float64
ELcount              10022 non-null float64
ELpct                10022 non-null float64
FOScount             10022 non-null float64
FOSpct               10022 non-null float64
HOMcount             10022 non-null float64
HOMpct               10022 non-null float64
MIGcount             10022 non-null float64
MIGpct               10022 non-null float64
SWDcount             0 non-null float64
SWDpct               0 non-null float64
FRPMcount            10022 non-null float64
FRPMpct              10022 non-null float64
TitleIStatus         10032 non-null object
DASS                 10032 non-null object
AssistStatusESSA     9861 non-null object
ELATested            9382 non-null float64
ELAStdMetPct         9382 non-null float64
MathTested           9375 non-null float64
MathStdMetPct        9375 non-null float64
CCPrepCohortCount    2202 non-null float64
CCPrepPct            2202 non-null float64
AbsentEligCount      9941 non-null float64
AbsentPct            9935 non-null float64
GradCohortCount      2258 non-null float64
GradPct              2258 non-null float64
UCCSUReqMetPct       2258 non-null float64
DropOutPct           2258 non-null float64
EnrollCumulative     9941 non-null float64
SuspPct              9941 non-null float64
dtypes: float64(57), int64(1), object(30)
memory usage: 6.7+ MB

In [ ]:
# Drop Street, CDCode
school.drop(['Street', 'CDCode'], axis=1)

In [ ]:
# Remove Charter Schools (Charter == N), CharterNum(?), FundingType

In [ ]:
# ClosedDate remove

In [ ]:
# Remove Virtual?

In [ ]:
# Investigate CongUS, AssemblyCA, SenateCA with Zillow data

In [ ]:
# investigate SchoolLevel, GradeLow, GradeHigh, SchoolType, EduOptions, LocSource

In [ ]:
# County vs CountyGeo

In [ ]:
# Investigate TitleIStatus, Title I funding

In [ ]:
# Dashboard Alternative School Status (DASS)?